Hw17
ArtanoHimself/ArtanoTMS pull request #10
Opened 2024-09-09 16:29 UTC by ArtanoHimself

2024-09-14 18:54 UTC, ArtanoHimself commented
https://github.com/user-attachments/assets/8cfd6663-d89a-4b3f-93c6-fe6abc47e16f

2024-09-20 08:37 UTC, numkms commented on hw17/hw17/ViewController.swift
> +        })
```suggestion
        UIView.animate(withDuration: 1, animations: { [weak self] in
            guard let self else { return }
            
            if playground.frame.height > circle.frame.origin.y + 70 {
                circle.frame = .init(x: circle.frame.origin.x,
                                     y: circle.frame.origin.y + 20,
                                     width: circle.frame.width,
                                     height: circle.frame.height)
            } else {
                circle.frame = .init(
                   x: circle.frame.origin.x,
                   y: (playground.bounds.height - 50),
                   width: circle.frame.width,
                   height: circle.frame.height
                )
            }
        })
```

2024-09-20 08:39 UTC, numkms commented on hw17/hw17/ViewController.swift
> +        })
Вот эти + 70, -50 значения - вынести в константы

2024-09-20 08:39 UTC, numkms requested changes
Поправить кодестайл, вынести магические числа в константы

2024-09-29 12:57 UTC, closed without merging